#!/usr/bin/env python3
"""Inject 6-lang copy for AI agent, WhatsApp, e-fatura, Trendyol, danışmanlık pages."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
I18N = ROOT / "src/i18n"

AG, WA, EF, TY, DN = "#c084fc", "#25d366", "#f59e0b", "#f27a1a", "#38bdf8"


def a(href: str, text: str, c: str) -> str:
    return f'<a href="{href}" style="color:{c}">{text}</a>'


def tel(c: str) -> str:
    return f'<a href="tel:+905465496806" style="color:{c}">+90 546 549 6806</a>'


PACKS: dict[str, dict] = {
    "tr": {
        "aiAgentPage": {
            "hero": {
                "badge": "Otonom · CRM · ERP · MCP · +90 546 549 6806",
                "title": "AI Agent Yaptırmak",
                "desc": f"AI agent yaptırmak: sohbet botu değil. E-posta sınıflar, CRM günceller, sipariş açar, rapor üretir. Kritik adımda insan onayı kuraldır. Çankaya — yazılı teklif, ücretsiz keşif. Konuşan bot {a('/chatbot-yaptirmak', 'chatbot yaptırmak', AG)} sayfasındadır. Rehber: {a('/blog/ankara-ai-agents-gelistirme-2026', 'AI agents', AG)}.",
            },
            "pricing": {
                "title": "AI agent fiyatı (2026)",
                "intro": "Fiyat araç sayısı, ERP ve on-premise’e göre değişir. Bantlar 2026 Ankara piyasasıdır; keşif ücretsiz, teklif yazılıdır.",
                "row1": "PoC / tek senaryo",
                "row2": "Çok araçlı kurumsal",
                "row3": "On-premise + MCP",
                "t1": "4–6 hafta",
                "t2": "8–14 hafta",
                "t3": "3–6 ay",
                "linkGuide": "AI agents rehberi",
                "linkBot": "Chatbot yaptırmak",
            },
            "cards": {
                "c1title": "📬 Operasyon",
                "c1desc": "Destek kuyruğu, sipariş, randevu. Agent araç çağırır; her adım loglanır. Kontrolsüz çalışmaz.",
                "c1link": "Keşif ayarla →",
                "c2title": "🔗 ERP / CRM",
                "c2desc": f"Logo, Netsis, özel API. Yanlış yazmasın diye onay kapısı konur. {a('/logo-netsis-entegrasyon', 'ERP entegrasyonu', AG)} aynı ekipte.",
                "c2link": "Logo Netsis →",
                "c3title": "🔄 RPA ile birlikte",
                "c3desc": f"RPA tıklar, agent karar verir. İkisi {a('/surec-otomasyonu', 'süreç otomasyonu', AG)} ile aynı projede olabilir.",
                "c3link": "Süreç otomasyonu →",
                "c4title": "💬 Chatbot değil",
                "c4desc": f"Sadece yanıt için {a('/chatbot-yaptirmak', 'chatbot', AG)} veya {a('/whatsapp-chatbot-yaptirmak', 'WhatsApp', AG)}. Bu sayfa iş yapan ajandır.",
                "c4link": "Chatbot yaptırmak →",
            },
            "who": {
                "title": "AI agent’ı kim yaptırır?",
                "intro": "“AI agent yaptırmak” ve “otonom yapay zeka” aynı sipariştir: modelin araç kullanması. Chatbot arayanlar konuşma sayfasına gider. Ozturksoft Çankaya’da hazır ajan satmaz; senaryo, yetki ve onay yazılı teslim edilir.",
                "i1": "Destek kuyruğu ve e-posta elle yürüyor. Agent sınıflasın, taslak yazsın, CRM’e kayıt düşsün; yanlış kaydı insan onaylasın.",
                "i2": "Sipariş veya randevu botta konuşuluyor ama sisteme yazılmıyor. Agent API çağırsın; Logo/Netsis aynı ekipte bağlansın.",
                "i3": "Kamu veya holding: on-premise, MCP, audit. Veri ağda kalsın. Model keşifte netleşir.",
                "i4": f"Önce konuşan bot, yarın ajan. {a('/chatbot-yaptirmak', 'Chatbot', AG)} ve agent aynı Çankaya ekibinde; tedarikçi parçalanmaz.",
                "outro": f"Rehber ayrıdır: {a('/blog/ankara-ai-agents-gelistirme-2026', 'AI agents yazısı', AG)}. Bu sayfa iş yaptırmak içindir. Ücretsiz keşif: {tel(AG)}.",
            },
            "faq": {
                "title": "Sık sorulanlar",
                "q1": "AI agent yaptırmak ne kadar tutar?",
                "a1": "PoC 60.000–120.000 TL (4–6 hafta), kurumsal 150.000–280.000 TL (8–14 hafta), on-premise + MCP 280.000–500.000+ TL. Keşif ücretsiz; net fiyat kapsam yazıldıktan sonra.",
                "q2": "Chatbot’tan farkı nedir?",
                "a2": f"Chatbot soru yanıtlar — {a('/chatbot-yaptirmak', 'chatbot yaptırmak', AG)}. Agent araç kullanır: e-posta, CRM, sipariş. İkisi aynı asistan ürününde birleşebilir: {a('/ankara-ai-asistan', 'AI Asistan', AG)}.",
                "q3": "Kontrolsüz mü çalışır?",
                "a3": "Hayır. Kritik adımlarda insan onayı kuraldır. Log ve yetki teslimata dahildir.",
                "q4": "ERP’ye bağlanır mı?",
                "a4": f"Evet. {a('/logo-netsis-entegrasyon', 'Logo, Netsis', AG)} ve özel API. Yanlış fiş yazılmasın diye onay kapısı konur.",
            },
            "cta": {
                "btn": "Ücretsiz keşif görüşmesi",
                "title": "Agent senaryonuzu konuşalım",
                "desc": f"Ücretsiz keşif — hangi görev, hangi sistem. {tel(AG)}",
                "btn2": "Ücretsiz teklif al",
            },
            "footer": "© 2026 Ozturksoft — AI agent yaptırmak",
            "related": {
                "bot": "Chatbot yaptırmak",
                "ai": "Yapay zeka entegrasyonu",
                "proc": "Süreç otomasyonu",
                "logo": "Logo Netsis",
                "hub": "Yapay zeka firması",
                "guide": "Rehber",
            },
            "meta": {"title": "AI Agent Yaptırmak | Otonom Yapay Zeka | Ozturksoft"},
            "stats": {"s1l": "PoC / tek senaryo", "s2l": "Kurumsal agent", "s3l": "Kurumsal teslim"},
        },
        "waChatbotPage": {
            "hero": {
                "badge": "Business API · GPT · CRM · +90 546 549 6806",
                "title": "WhatsApp Chatbot Yaptırmak",
                "desc": f"WhatsApp chatbot yaptırmak: 7/24 sipariş, fiyat ve SSS. Resmi Business API, GPT/RAG, CRM. Çankaya — yazılı teklif, ücretsiz keşif. Site widget ayrıdır: {a('/chatbot-yaptirmak', 'chatbot yaptırmak', WA)}. Rehber: {a('/blog/whatsapp-chatbot-isletme-rehberi-2026', 'WhatsApp rehberi', WA)}.",
            },
            "pricing": {
                "title": "WhatsApp chatbot fiyatı (2026)",
                "intro": "Fiyat senaryo, GPT ve CRM’e göre değişir. Meta mesaj ücreti ayrıca. Bantlar 2026 Ankara piyasasıdır; keşif ücretsiz, teklif yazılıdır.",
                "row1": "WhatsApp FAQ",
                "row2": "WhatsApp GPT / AI",
                "row3": "WhatsApp + CRM / ERP",
                "t1": "3–5 hafta",
                "t2": "4–8 hafta",
                "t3": "6–12 hafta",
                "linkWeb": "Web chatbot (site widget)",
                "linkGuide": "WhatsApp rehberi",
            },
            "cards": {
                "c1title": "💬 7/24 yanıt",
                "c1desc": "Mesai dışında sipariş, fiyat, kargo. Zor soru insana devredilir. Şablon mesaj resmi API ile gider.",
                "c1link": "Keşif ayarla →",
                "c2title": "🔗 CRM ve stok",
                "c2desc": f"Sipariş, randevu, bakiye. {a('/logo-netsis-entegrasyon', 'Logo / Netsis', WA)} veya özel API. Çift kayıt bitmez.",
                "c2link": "ERP bağla →",
                "c3title": "🌐 Web ayrı kanal",
                "c3desc": f"Site köşe sohbeti {a('/chatbot-yaptirmak', 'chatbot yaptırmak', WA)} sayfasındadır. Aynı asistan iki kanala çıkar.",
                "c3link": "Web chatbot →",
                "c4title": "🔒 KVKK",
                "c4desc": f"On-premise veya TR barındırma, log, silme politikası. Kurumsal paket {a('/ankara-ai-asistan', 'AI Asistan', WA)}.",
                "c4link": "AI Asistan →",
            },
            "who": {
                "title": "WhatsApp botunu kim yaptırır?",
                "intro": "“WhatsApp chatbot yaptırmak” kanal siparişidir: müşteri zaten WhatsApp’ta. Site botu ayrı URL’dedir. Ozturksoft BSP başvurusunu birlikte yürütür; hazır kutu bot satılmaz.",
                "i1": "Sipariş ve fiyat WhatsApp’tan geliyor, gece yanıt yok. Bot katalog ve kargo sorsun; zor kayıt insana düşsün.",
                "i2": "Resmi şablon ve toplu bilgilendirme lazım. Business API şart; başvuruyu birlikte açarız.",
                "i3": f"WhatsApp + site aynı asistan olsun. Web {a('/chatbot-yaptirmak', 'chatbot', WA)} sayfasında eklenir.",
                "i4": f"Sipariş ERP’ye yazılsın. {a('/logo-netsis-entegrasyon', 'Logo', WA)} veya {a('/e-ticaret-sitesi-yaptirmak', 'e-ticaret', WA)} aynı Çankaya ekibinde.",
                "outro": f"Rehber ayrıdır. Bu sayfa iş yaptırmak içindir. Ücretsiz keşif: {tel(WA)}.",
            },
            "faq": {
                "title": "Sık sorulanlar",
                "q1": "WhatsApp chatbot yaptırmak ne kadar?",
                "a1": "FAQ 40.000–70.000 TL, GPT 60.000–100.000 TL, CRM/ERP 90.000–160.000 TL. Meta mesaj ve OpenAI aylık ayrıca. Keşif ücretsizdir.",
                "q2": "Business API şart mı?",
                "a2": "Resmi otomasyon ve şablon için evet. BSP ve numara doğrulamayı birlikte yürütürüz. Meta onayı süre ekleyebilir.",
                "q3": "Web sitesine de eklenir mi?",
                "a3": f"Evet. Widget {a('/chatbot-yaptirmak', 'chatbot yaptırmak', WA)} sayfasındadır; aynı asistan paylaşılır.",
                "q4": "Ne kadar sürer?",
                "a4": "FAQ 3–5 hafta, GPT 4–8 hafta, CRM 6–12 hafta. BSP beklerken senaryo yazılır.",
            },
            "cta": {
                "btn": "Ücretsiz keşif görüşmesi",
                "title": "WhatsApp botunuzu planlayalım",
                "desc": f"Ücretsiz keşif — senaryo, API, bütçe. {tel(WA)}",
                "btn2": "Ücretsiz teklif al",
            },
            "footer": "© 2026 Ozturksoft — WhatsApp chatbot yaptırmak",
            "related": {
                "bot": "Chatbot yaptırmak",
                "shop": "E-ticaret",
                "agent": "AI agent",
                "asistan": "AI Asistan",
                "hub": "Yapay zeka firması",
                "guide": "Rehber",
            },
            "meta": {"title": "WhatsApp Chatbot Yaptırmak | Business API | Ozturksoft"},
            "stats": {"s1l": "WhatsApp GPT", "s2l": "Canlıya alma", "s3n": "BSP", "s3l": "API başvurusu bizde"},
        },
        "efaturaPage": {
            "hero": {
                "badge": "GİB · E-Arşiv · E-İrsaliye · Logo · +90 546 549 6806",
                "title": "E-Fatura Entegrasyonu",
                "desc": f"E-fatura entegrasyonu: GİB’e resmi e-belge. Gelen/giden fatura {a('/logo-netsis-entegrasyon', 'Logo veya Netsis', EF)} fişine düşer. Kâğıt tarama değil — o iş {a('/fatura-okuma', 'fatura okuma', EF)} sayfasındadır. Çankaya, yazılı teklif, ücretsiz keşif.",
            },
            "pricing": {
                "title": "E-fatura entegrasyonu fiyatı (2026)",
                "intro": "Fiyat belge tipi, özel entegratör ve ERP’ye göre değişir. Bantlar 2026 Ankara piyasasıdır; keşif ücretsiz, teklif yazılıdır. Entegratör lisans ücreti ayrıca.",
                "row1": "Tek ERP bağlayıcı",
                "row2": "E-arşiv + e-irsaliye",
                "row3": "Holding / çok şube",
                "t1": "3–6 hafta",
                "t2": "6–10 hafta",
                "t3": "3–5 ay",
                "linkOcr": "Fatura okuma (OCR)",
                "linkLogo": "Logo Netsis",
            },
            "cards": {
                "c1title": "📨 Gelen / giden e-fatura",
                "c1desc": "GİB veya özel entegratör kuyruğu. UBL, imza, reddetme/kabul. Portal tıklamak bitmez.",
                "c1link": "Keşif ayarla →",
                "c2title": "🔗 Logo / Netsis fişi",
                "c2desc": f"E-belge muhasebe kaydına yazılır. Çift giriş biter. {a('/logo-netsis-entegrasyon', 'ERP API', EF)} aynı projede.",
                "c2link": "ERP bağla →",
                "c3title": "📦 E-irsaliye / e-arşiv",
                "c3desc": "Sevk ve e-arşiv aynı bağlayıcıda. E-ticaret siparişi faturaya düşer.",
                "c3link": "E-ticaret yaptırmak →",
                "c4title": "📷 OCR değil",
                "c4desc": f"Kâğıt veya WhatsApp fotoğrafı {a('/fatura-okuma', 'fatura okuma programı', EF)}dır. Bu URL resmi e-belgedir.",
                "c4link": "Fatura okuma →",
            },
            "who": {
                "title": "E-fatura entegrasyonunu kim yaptırır?",
                "intro": "“E-fatura entegrasyonu” GİB’e bağlanmaktır. Portal + Excel yetmez. OCR arayanlar fatura okuma sayfasına gider. Ozturksoft bağlayıcıyı sizin ERP’nize yazar; kutu lisans satmaz.",
                "i1": "Gelen e-fatura portaldan indirilip elle Logo’ya yazılıyor. Kuyruk ve son gün hatası bitsin.",
                "i2": f"E-ticaret veya saha siparişi e-fatura kessin. {a('/e-ticaret-sitesi-yaptirmak', 'Mağaza', EF)} veya {a('/trendyol-entegrasyonu', 'Trendyol', EF)} aynı ekipte bağlanır.",
                "i3": "E-irsaliye ve e-arşiv aynı anda. Çok şube, holding mali işler.",
                "i4": f"Kâğıt tedarikçi faturası da var. OCR {a('/fatura-okuma', 'ayrı', EF)}; ikisi birlikte yürüyebilir.",
                "outro": f"Ücretsiz keşif: {tel(EF)}.",
            },
            "faq": {
                "title": "Sık sorulanlar",
                "q1": "E-fatura entegrasyonu ne kadar tutar?",
                "a1": "Bağlayıcı 35.000–70.000 TL (3–6 hafta), e-arşiv + e-irsaliye 70.000–140.000 TL, holding 140.000–280.000+ TL. Entegratör ücreti ayrıca. Keşif ücretsizdir.",
                "q2": "Fatura okuma ile karışır mı?",
                "a2": f"Hayır. OCR fotoğraf/PDF okur: {a('/fatura-okuma', 'fatura okuma', EF)}. Bu sayfa GİB e-belge API’sidir.",
                "q3": "Logo / Netsis yazar mı?",
                "a3": f"Evet. Gelen ve giden belge {a('/logo-netsis-entegrasyon', 'Logo, Netsis', EF)} fişine düşer.",
                "q4": "Özel entegratör şart mı?",
                "a4": "Çoğu projede evet. Mevcut entegratörünüz varsa ona bağlarız; yoksa keşifte seçilir.",
            },
            "cta": {
                "btn": "Ücretsiz keşif görüşmesi",
                "title": "E-fatura bağlayıcısını konuşalım",
                "desc": f"Ücretsiz keşif — GİB, ERP, bütçe. {tel(EF)}",
                "btn2": "Ücretsiz teklif al",
            },
            "footer": "© 2026 Ozturksoft — E-fatura entegrasyonu",
            "related": {
                "ocr": "Fatura okuma",
                "logo": "Logo Netsis",
                "ty": "Trendyol",
                "shop": "E-ticaret",
                "proc": "Süreç otomasyonu",
            },
            "meta": {"title": "E-Fatura Entegrasyonu | GİB & ERP | Ozturksoft"},
            "stats": {"s1l": "Tek ERP bağlayıcı", "s2l": "E-arşiv + e-irsaliye", "s3l": "Bağlayıcı teslim"},
        },
        "trendyolPage": {
            "hero": {
                "badge": "Sipariş · Stok · Kargo · Logo · +90 546 549 6806",
                "title": "Trendyol Entegrasyonu",
                "desc": f"Trendyol entegrasyonu: sipariş panelden kopyalanmasın. Stok, kargo, iade API ile yürür. Kendi mağaza ayrıdır — {a('/e-ticaret-sitesi-yaptirmak', 'e-ticaret sitesi yaptırmak', TY)}. Çankaya, yazılı teklif, ücretsiz keşif.",
            },
            "pricing": {
                "title": "Trendyol entegrasyonu fiyatı (2026)",
                "intro": "Fiyat sipariş hacmi, kargo ve ERP’ye göre değişir. Bantlar 2026 Ankara piyasasıdır; keşif ücretsiz, teklif yazılıdır.",
                "row1": "Sipariş çekme",
                "row2": "Stok + kargo",
                "row3": "Pazaryeri + ERP",
                "t1": "2–4 hafta",
                "t2": "4–8 hafta",
                "t3": "8–14 hafta",
                "linkShop": "Kendi e-ticaret sitesi",
                "linkLogo": "Logo Netsis",
            },
            "cards": {
                "c1title": "📦 Sipariş",
                "c1desc": "Yeni sipariş panele düşer, yazıcı veya depo kuyruğuna gider. Excel kopyala biter.",
                "c1link": "Keşif ayarla →",
                "c2title": "📊 Stok senkron",
                "c2desc": f"Satış stoku Logo’dan veya mağazadan geri yazar. Çift satış ve eksi stok kesilir. {a('/logo-netsis-entegrasyon', 'ERP', TY)} aynı ekipte.",
                "c2link": "ERP bağla →",
                "c3title": "🚚 Kargo ve iade",
                "c3desc": f"Takip numarası, iade kabul. Yurtiçi/Aras API. E-fatura aynı siparişten kesilir: {a('/e-fatura-entegrasyonu', 'e-fatura', TY)}.",
                "c3link": "E-fatura bağla →",
                "c4title": "🏪 Kendi mağaza ayrı",
                "c4desc": f"Komisyonsuz kendi site {a('/e-ticaret-sitesi-yaptirmak', 'e-ticaret yaptırmak', TY)}. Pazaryeri stoku ile site stoku çakışmaz.",
                "c4link": "E-ticaret sitesi →",
            },
            "who": {
                "title": "Trendyol entegrasyonunu kim yaptırır?",
                "intro": "“Trendyol entegrasyonu” pazaryeri API siparişidir. Kendi mağaza arayanlar e-ticaret sayfasına gider. Ozturksoft hazır pazaryeri paketi satmaz; sipariş, stok ve ERP sizin akışınıza yazılır.",
                "i1": "Sipariş panelden kopyalanıyor, stok gece eksiye düşüyor. API çeksin, stok geri yazsın.",
                "i2": "Hepsiburada veya N11 aynı stoktan gitsin. İkinci kanal aynı omurgaya eklenir.",
                "i3": f"Fatura Logo’dan kessin. {a('/e-fatura-entegrasyonu', 'E-fatura', TY)} ve {a('/logo-netsis-entegrasyon', 'ERP', TY)} aynı Çankaya ekibinde.",
                "i4": f"Kendi marka mağazası da olsun. Site {a('/e-ticaret-sitesi-yaptirmak', 'ayrı URL', TY)}; stok tek kaynaktan.",
                "outro": f"Ücretsiz keşif: {tel(TY)}.",
            },
            "faq": {
                "title": "Sık sorulanlar",
                "q1": "Trendyol entegrasyonu ne kadar tutar?",
                "a1": "Sipariş 25.000–50.000 TL (2–4 hafta), stok+kargo 50.000–95.000 TL, ERP 95.000–180.000 TL. Keşif ücretsizdir.",
                "q2": "E-ticaret sitesi bu mu?",
                "a2": f"Hayır. Kendi mağaza {a('/e-ticaret-sitesi-yaptirmak', 'e-ticaret sitesi yaptırmak', TY)}. Bu sayfa Trendyol/pazaryeri API’sidir.",
                "q3": "Hepsiburada eklenir mi?",
                "a3": "Evet. Aynı stok omurgasına ikinci pazaryeri yazılır. Fiyat keşifte kanal sayısına göre.",
                "q4": "Logo’ya sipariş düşer mi?",
                "a4": f"Evet. {a('/logo-netsis-entegrasyon', 'Logo / Netsis', TY)} fişi ve isteğe {a('/e-fatura-entegrasyonu', 'e-fatura', TY)} aynı projede.",
            },
            "cta": {
                "btn": "Ücretsiz keşif görüşmesi",
                "title": "Pazaryeri akışını konuşalım",
                "desc": f"Ücretsiz keşif — sipariş, stok, ERP. {tel(TY)}",
                "btn2": "Ücretsiz teklif al",
            },
            "footer": "© 2026 Ozturksoft — Trendyol entegrasyonu",
            "related": {
                "shop": "E-ticaret yaptırmak",
                "ef": "E-fatura",
                "logo": "Logo Netsis",
                "wa": "WhatsApp chatbot",
            },
            "meta": {"title": "Trendyol Entegrasyonu | Sipariş & Stok | Ozturksoft"},
            "stats": {"s1l": "Sipariş çekme", "s2l": "Stok + kargo", "s3l": "Stok teslim"},
        },
        "danismanlikPage": {
            "hero": {
                "badge": "Yol haritası · PoC · KVKK · +90 546 549 6806",
                "title": "Yapay Zeka Danışmanlığı",
                "desc": f"Yapay zeka danışmanlığı: ChatGPT hesabı strateji değildir. Hangi süreç, hangi bütçe, veri dışarı çıkar mı — yazılı yol haritası. Uygulama ayrı sipariştir: {a('/yapay-zeka-entegrasyonu', 'entegrasyon', DN)}, {a('/chatbot-yaptirmak', 'chatbot', DN)}, {a('/ai-agent', 'agent', DN)}. Çankaya, ücretsiz keşif. Rehber: {a('/blog/yapay-zeka-danismanligi-isletmeler-rehberi-2026', 'danışmanlık yazısı', DN)}.",
            },
            "pricing": {
                "title": "Yapay zeka danışmanlığı fiyatı (2026)",
                "intro": "Keşif ücretsizdir. Yol ve PoC yazılı teslim edilir; kod ayrı tekliftir. Bantlar 2026 Ankara piyasasıdır.",
                "row1": "Keşif",
                "row2": "Yol haritası",
                "row3": "PoC",
                "p1": "Ücretsiz",
                "t1": "45–90 dk",
                "t2": "1–3 hafta",
                "t3": "4–8 hafta",
                "linkAi": "Uygulama: entegrasyon",
                "linkGuide": "Rehber",
            },
            "cards": {
                "c1title": "🗺️ Süreç seçimi",
                "c1desc": "Destek, evrak, satış — hangisi 90 günde para kazandırır. Liste yazılıdır; slayt teslimi yoktur.",
                "c1link": "Keşif ayarla →",
                "c2title": "💰 Maliyet bandı",
                "c2desc": "Chatbot, RAG, agent ayrı fiyatlanır. Sürpriz yok. Uygulama aynı ekipte tekliflenir.",
                "c2link": "Entegrasyon fiyatı →",
                "c3title": "🔒 KVKK",
                "c3desc": f"Veri dışarı çıkar mı, on-premise şart mı. {a('/ankara-kamu-yapay-zeka', 'Kamu', DN)} ve holding için mimari notu.",
                "c3link": "KVKK rehberi →",
                "c4title": "🛠️ Sonra kod",
                "c4desc": f"Karar netleşince {a('/chatbot-yaptirmak', 'chatbot', DN)}, {a('/ai-agent', 'agent', DN)} veya LLM aynı Çankaya ekibinde yapılır.",
                "c4link": "Yapay zeka firması →",
            },
            "who": {
                "title": "Danışmanlığı kim yaptırır?",
                "intro": "“Yapay zeka danışmanlığı” henüz ne yaptıracağını bilmeyen sipariştir. ChatGPT entegrasyonu arayanlar uygulama sayfasına gider. Ozturksoft önce yol yazar; isterseniz aynı ekip kodlar.",
                "i1": "Yönetim “AI yapın” dedi, süreç listesi yok. 90 günlük yol ve bütçe bandı yazılı olsun.",
                "i2": f"Hazır bot aldınız, uymadı. PoC ile doğru senaryo kanıtlansın; sonra {a('/chatbot-yaptirmak', 'chatbot', DN)} veya {a('/ai-agent', 'agent', DN)}.",
                "i3": f"KVKK ve kamu. On-premise şart mı, keşifte yazılır. Uygulama {a('/yapay-zeka-entegrasyonu', 'entegrasyon', DN)} veya {a('/ankara-kamu-yapay-zeka', 'kamu AI', DN)}.",
                "i4": f"Rehber okudunuz. Bilgi yazısı {a('/blog/yapay-zeka-danismanligi-isletmeler-rehberi-2026', 'ayrı', DN)}; iş bu sayfadan başlar.",
                "outro": f"Ücretsiz keşif: {tel(DN)}.",
            },
            "faq": {
                "title": "Sık sorulanlar",
                "q1": "Yapay zeka danışmanlığı ne kadar tutar?",
                "a1": "Keşif ücretsiz. Yol haritası 25.000–60.000 TL (1–3 hafta), PoC 40.000–80.000 TL. Yazılım ayrı tekliftir.",
                "q2": "Entegrasyon ile farkı nedir?",
                "a2": f"Burası nereden başlanır. Kod {a('/yapay-zeka-entegrasyonu', 'yapay zeka entegrasyonu', DN)}, {a('/chatbot-yaptirmak', 'chatbot', DN)}, {a('/ai-agent', 'AI agent', DN)} sayfalarındadır.",
                "q3": "Sadece slayt mı?",
                "a3": "Hayır. Süreç listesi, maliyet bandı, 90 günlük sıra. İsterseniz aynı ekip uygular.",
                "q4": "Keşif gerçekten ücretsiz mi?",
                "a4": f"Evet. 45–90 dk, bağlayıcı yok. {a('/iletisim', 'Form', DN)} veya {tel(DN)}.",
            },
            "cta": {
                "btn": "Ücretsiz keşif görüşmesi",
                "title": "Yol haritasını konuşalım",
                "desc": f"Ücretsiz keşif — süreç, KVKK, bütçe. {tel(DN)}",
                "btn2": "Ücretsiz teklif al",
            },
            "footer": "© 2026 Ozturksoft — Yapay zeka danışmanlığı",
            "related": {
                "ai": "Entegrasyon",
                "bot": "Chatbot",
                "agent": "AI agent",
                "hub": "Yapay zeka firması",
                "guide": "Rehber",
            },
            "meta": {"title": "Yapay Zeka Danışmanlığı | Yol Haritası | Ozturksoft"},
            "stats": {"s1n": "Ücretsiz", "s1l": "Keşif görüşmesi", "s2l": "Yol haritası", "s3l": "PoC"},
        },
    }
}

# English — commercial, prices stay TL
PACKS["en"] = {
    "aiAgentPage": {
        "hero": {
            "badge": "Autonomous · CRM · ERP · MCP · +90 546 549 6806",
            "title": "AI Agent Yaptırmak",
            "desc": f"Have an AI agent built: not a chat bot. It classifies email, updates CRM, opens orders, writes reports. Human approval is required on critical steps. Çankaya — written quote, free discovery. Talking bots live on {a('/chatbot-yaptirmak', 'have a chatbot built', AG)}. Guide: {a('/blog/ankara-ai-agents-gelistirme-2026', 'AI agents', AG)}.",
        },
        "pricing": {
            "title": "AI agent price (2026)",
            "intro": "Price follows tool count, ERP and on-premise. Bands are 2026 Ankara market; discovery is free, the quote is written.",
            "row1": "PoC / one scenario",
            "row2": "Multi-tool enterprise",
            "row3": "On-premise + MCP",
            "t1": "4–6 weeks",
            "t2": "8–14 weeks",
            "t3": "3–6 months",
            "linkGuide": "AI agents guide",
            "linkBot": "Have a chatbot built",
        },
        "cards": {
            "c1title": "📬 Operations",
            "c1desc": "Support queues, orders, appointments. The agent calls tools; every step is logged. It does not run unchecked.",
            "c1link": "Book discovery →",
            "c2title": "🔗 ERP / CRM",
            "c2desc": f"Logo, Netsis, custom API. An approval gate stops bad writes. {a('/logo-netsis-entegrasyon', 'ERP integration', AG)} is the same team.",
            "c2link": "Logo Netsis →",
            "c3title": "🔄 With RPA",
            "c3desc": f"RPA clicks, the agent decides. Both can sit in the same {a('/surec-otomasyonu', 'process automation', AG)} project.",
            "c3link": "Process automation →",
            "c4title": "💬 Not a chatbot",
            "c4desc": f"Answers only: {a('/chatbot-yaptirmak', 'chatbot', AG)} or {a('/whatsapp-chatbot-yaptirmak', 'WhatsApp', AG)}. This page is an agent that does work.",
            "c4link": "Have a chatbot built →",
        },
        "who": {
            "title": "Who commissions an AI agent?",
            "intro": "“Have an AI agent built” and “autonomous AI” are the same order: the model using tools. Chatbot searchers go to the conversation page. Ozturksoft in Çankaya does not sell a boxed agent; scenario, permissions and approval are delivered in writing.",
            "i1": "Support queues and email still run by hand. The agent should classify, draft and write CRM; a human should approve a bad record.",
            "i2": "Orders or appointments are discussed in a bot but never written to the system. The agent should call APIs; Logo/Netsis joins the same team.",
            "i3": "Public sector or holding: on-premise, MCP, audit. Data stays on the network. The model is fixed in discovery.",
            "i4": f"Talking bot first, agent tomorrow. {a('/chatbot-yaptirmak', 'Chatbot', AG)} and agent stay in one Çankaya team; vendors are not split.",
            "outro": f"The guide is separate: {a('/blog/ankara-ai-agents-gelistirme-2026', 'AI agents article', AG)}. This page is for commissioning work. Free discovery: {tel(AG)}.",
        },
        "faq": {
            "title": "FAQ",
            "q1": "How much does an AI agent cost?",
            "a1": "PoC 60,000–120,000 TL (4–6 weeks), enterprise 150,000–280,000 TL (8–14 weeks), on-premise + MCP 280,000–500,000+ TL. Discovery is free; a firm price after scope.",
            "q2": "How is it different from a chatbot?",
            "a2": f"A chatbot answers questions — {a('/chatbot-yaptirmak', 'have a chatbot built', AG)}. An agent uses tools: email, CRM, orders. Both can merge in {a('/ankara-ai-asistan', 'AI Assistant', AG)}.",
            "q3": "Does it run unchecked?",
            "a3": "No. Human approval is required on critical steps. Logs and permissions are in the delivery.",
            "q4": "Can it connect to ERP?",
            "a4": f"Yes. {a('/logo-netsis-entegrasyon', 'Logo, Netsis', AG)} and custom APIs. An approval gate stops a wrong voucher.",
        },
        "cta": {
            "btn": "Free discovery call",
            "title": "Let’s talk through your agent scenario",
            "desc": f"Free discovery — which task, which system. {tel(AG)}",
            "btn2": "Get a free quote",
        },
        "footer": "© 2026 Ozturksoft — Have an AI agent built",
        "related": {
            "bot": "Have a chatbot built",
            "ai": "AI integration",
            "proc": "Process automation",
            "logo": "Logo Netsis",
            "hub": "AI company",
            "guide": "Guide",
        },
        "meta": {"title": "Have an AI Agent Built | Autonomous AI | Ozturksoft"},
        "stats": {"s1l": "PoC / one scenario", "s2l": "Enterprise agent", "s3l": "Enterprise delivery"},
    },
    "waChatbotPage": {
        "hero": {
            "badge": "Business API · GPT · CRM · +90 546 549 6806",
            "title": "WhatsApp Chatbot Yaptırmak",
            "desc": f"Have a WhatsApp chatbot built: 24/7 orders, prices and FAQ. Official Business API, GPT/RAG, CRM. Çankaya — written quote, free discovery. The site widget is separate: {a('/chatbot-yaptirmak', 'have a chatbot built', WA)}. Guide: {a('/blog/whatsapp-chatbot-isletme-rehberi-2026', 'WhatsApp guide', WA)}.",
        },
        "pricing": {
            "title": "WhatsApp chatbot price (2026)",
            "intro": "Price follows scenarios, GPT and CRM. Meta message fees are extra. Bands are 2026 Ankara market; discovery is free, the quote is written.",
            "row1": "WhatsApp FAQ",
            "row2": "WhatsApp GPT / AI",
            "row3": "WhatsApp + CRM / ERP",
            "t1": "3–5 weeks",
            "t2": "4–8 weeks",
            "t3": "6–12 weeks",
            "linkWeb": "Web chatbot (site widget)",
            "linkGuide": "WhatsApp guide",
        },
        "cards": {
            "c1title": "💬 24/7 answers",
            "c1desc": "Orders, prices, shipping after hours. Hard questions hand off to a human. Template messages go via the official API.",
            "c1link": "Book discovery →",
            "c2title": "🔗 CRM and stock",
            "c2desc": f"Orders, appointments, balances. {a('/logo-netsis-entegrasyon', 'Logo / Netsis', WA)} or a custom API. Duplicate records stop.",
            "c2link": "Connect ERP →",
            "c3title": "🌐 Web is a separate channel",
            "c3desc": f"Corner chat on the site lives on {a('/chatbot-yaptirmak', 'have a chatbot built', WA)}. The same assistant can serve both channels.",
            "c3link": "Web chatbot →",
            "c4title": "🔒 KVKK",
            "c4desc": f"On-premise or TR hosting, logs, deletion policy. The enterprise pack is {a('/ankara-ai-asistan', 'AI Assistant', WA)}.",
            "c4link": "AI Assistant →",
        },
        "who": {
            "title": "Who commissions a WhatsApp bot?",
            "intro": "“Have a WhatsApp chatbot built” is a channel order: the customer is already on WhatsApp. The site bot has its own URL. Ozturksoft runs the BSP application with you; no boxed bot is sold.",
            "i1": "Orders and prices arrive on WhatsApp, nights go unanswered. The bot should handle catalogue and shipping; hard records go to a human.",
            "i2": "You need official templates and bulk notices. Business API is required; we open the application together.",
            "i3": f"WhatsApp + site should share one assistant. Web is added on {a('/chatbot-yaptirmak', 'chatbot', WA)}.",
            "i4": f"Orders should write to ERP. {a('/logo-netsis-entegrasyon', 'Logo', WA)} or {a('/e-ticaret-sitesi-yaptirmak', 'e-commerce', WA)} is the same Çankaya team.",
            "outro": f"The guide is separate. This page is for commissioning work. Free discovery: {tel(WA)}.",
        },
        "faq": {
            "title": "FAQ",
            "q1": "How much does a WhatsApp chatbot cost?",
            "a1": "FAQ 40,000–70,000 TL, GPT 60,000–100,000 TL, CRM/ERP 90,000–160,000 TL. Meta messages and OpenAI are monthly extras. Discovery is free.",
            "q2": "Is Business API required?",
            "a2": "Yes for official automation and templates. We run BSP and number verification with you. Meta approval can add time.",
            "q3": "Can it also go on the website?",
            "a3": f"Yes. The widget lives on {a('/chatbot-yaptirmak', 'have a chatbot built', WA)}; the same assistant is shared.",
            "q4": "How long does it take?",
            "a4": "FAQ 3–5 weeks, GPT 4–8 weeks, CRM 6–12 weeks. Scenarios are written while BSP is pending.",
        },
        "cta": {
            "btn": "Free discovery call",
            "title": "Let’s plan your WhatsApp bot",
            "desc": f"Free discovery — scenarios, API, budget. {tel(WA)}",
            "btn2": "Get a free quote",
        },
        "footer": "© 2026 Ozturksoft — Have a WhatsApp chatbot built",
        "related": {
            "bot": "Have a chatbot built",
            "shop": "E-commerce",
            "agent": "AI agent",
            "asistan": "AI Assistant",
            "hub": "AI company",
            "guide": "Guide",
        },
        "meta": {"title": "Have a WhatsApp Chatbot Built | Business API | Ozturksoft"},
        "stats": {"s1l": "WhatsApp GPT", "s2l": "Go-live", "s3n": "BSP", "s3l": "We handle the API application"},
    },
    "efaturaPage": {
        "hero": {
            "badge": "GİB · E-Archive · E-Dispatch · Logo · +90 546 549 6806",
            "title": "E-Fatura Entegrasyonu",
            "desc": f"E-invoice integration: official e-documents to GİB. Inbound/outbound invoices post to a {a('/logo-netsis-entegrasyon', 'Logo or Netsis', EF)} voucher. Not paper scanning — that job is {a('/fatura-okuma', 'invoice OCR', EF)}. Çankaya, written quote, free discovery.",
        },
        "pricing": {
            "title": "E-invoice integration price (2026)",
            "intro": "Price follows document types, the private integrator and ERP. Bands are 2026 Ankara market; discovery is free, the quote is written. Integrator licence fees are extra.",
            "row1": "Single ERP connector",
            "row2": "E-archive + e-dispatch",
            "row3": "Holding / multi-branch",
            "t1": "3–6 weeks",
            "t2": "6–10 weeks",
            "t3": "3–5 months",
            "linkOcr": "Invoice OCR",
            "linkLogo": "Logo Netsis",
        },
        "cards": {
            "c1title": "📨 Inbound / outbound e-invoice",
            "c1desc": "GİB or private-integrator queue. UBL, signature, reject/accept. Portal clicking stops.",
            "c1link": "Book discovery →",
            "c2title": "🔗 Logo / Netsis voucher",
            "c2desc": f"The e-document writes an accounting record. Double entry stops. {a('/logo-netsis-entegrasyon', 'ERP API', EF)} is the same project.",
            "c2link": "Connect ERP →",
            "c3title": "📦 E-dispatch / e-archive",
            "c3desc": "Despatch and e-archive on the same connector. E-commerce orders become invoices.",
            "c3link": "Have an e-commerce site built →",
            "c4title": "📷 Not OCR",
            "c4desc": f"Paper or WhatsApp photos are {a('/fatura-okuma', 'invoice OCR software', EF)}. This URL is official e-documents.",
            "c4link": "Invoice OCR →",
        },
        "who": {
            "title": "Who commissions e-invoice integration?",
            "intro": "“E-invoice integration” is connecting to GİB. Portal + Excel is not enough. OCR searchers go to invoice reading. Ozturksoft writes the connector to your ERP; it does not sell a boxed licence.",
            "i1": "Inbound e-invoices are downloaded from the portal and typed into Logo. Queue and last-day errors should stop.",
            "i2": f"E-commerce or field orders should issue e-invoices. {a('/e-ticaret-sitesi-yaptirmak', 'Store', EF)} or {a('/trendyol-entegrasyonu', 'Trendyol', EF)} joins the same team.",
            "i3": "E-dispatch and e-archive at once. Multi-branch, holding finance.",
            "i4": f"You also have paper supplier invoices. OCR is {a('/fatura-okuma', 'separate', EF)}; both can run together.",
            "outro": f"Free discovery: {tel(EF)}.",
        },
        "faq": {
            "title": "FAQ",
            "q1": "How much does e-invoice integration cost?",
            "a1": "Connector 35,000–70,000 TL (3–6 weeks), e-archive + e-dispatch 70,000–140,000 TL, holding 140,000–280,000+ TL. Integrator fees extra. Discovery is free.",
            "q2": "Is it the same as invoice OCR?",
            "a2": f"No. OCR reads photos/PDFs: {a('/fatura-okuma', 'invoice OCR', EF)}. This page is the GİB e-document API.",
            "q3": "Does it write Logo / Netsis?",
            "a3": f"Yes. Inbound and outbound documents post to a {a('/logo-netsis-entegrasyon', 'Logo, Netsis', EF)} voucher.",
            "q4": "Is a private integrator required?",
            "a4": "In most projects yes. If you already have one we connect to it; otherwise it is chosen in discovery.",
        },
        "cta": {
            "btn": "Free discovery call",
            "title": "Let’s talk through the e-invoice connector",
            "desc": f"Free discovery — GİB, ERP, budget. {tel(EF)}",
            "btn2": "Get a free quote",
        },
        "footer": "© 2026 Ozturksoft — E-invoice integration",
        "related": {
            "ocr": "Invoice OCR",
            "logo": "Logo Netsis",
            "ty": "Trendyol",
            "shop": "E-commerce",
            "proc": "Process automation",
        },
        "meta": {"title": "E-Invoice Integration | GİB & ERP | Ozturksoft"},
        "stats": {"s1l": "Single ERP connector", "s2l": "E-archive + e-dispatch", "s3l": "Connector delivery"},
    },
    "trendyolPage": {
        "hero": {
            "badge": "Orders · Stock · Shipping · Logo · +90 546 549 6806",
            "title": "Trendyol Entegrasyonu",
            "desc": f"Trendyol integration: orders should not be copied from the panel. Stock, shipping and returns run via API. Your own store is separate — {a('/e-ticaret-sitesi-yaptirmak', 'have an e-commerce site built', TY)}. Çankaya, written quote, free discovery.",
        },
        "pricing": {
            "title": "Trendyol integration price (2026)",
            "intro": "Price follows order volume, shipping and ERP. Bands are 2026 Ankara market; discovery is free, the quote is written.",
            "row1": "Order pull",
            "row2": "Stock + shipping",
            "row3": "Marketplace + ERP",
            "t1": "2–4 weeks",
            "t2": "4–8 weeks",
            "t3": "8–14 weeks",
            "linkShop": "Your own e-commerce site",
            "linkLogo": "Logo Netsis",
        },
        "cards": {
            "c1title": "📦 Orders",
            "c1desc": "New orders land in the panel, printer or warehouse queue. Copy-paste from Excel stops.",
            "c1link": "Book discovery →",
            "c2title": "📊 Stock sync",
            "c2desc": f"Sold stock writes back from Logo or the store. Double-sell and negative stock stop. {a('/logo-netsis-entegrasyon', 'ERP', TY)} is the same team.",
            "c2link": "Connect ERP →",
            "c3title": "🚚 Shipping and returns",
            "c3desc": f"Tracking numbers, return accept. Yurtiçi/Aras API. E-invoices cut from the same order: {a('/e-fatura-entegrasyonu', 'e-invoice', TY)}.",
            "c3link": "Connect e-invoice →",
            "c4title": "🏪 Own store is separate",
            "c4desc": f"Commission-free own site: {a('/e-ticaret-sitesi-yaptirmak', 'have e-commerce built', TY)}. Marketplace stock and site stock do not clash.",
            "c4link": "E-commerce site →",
        },
        "who": {
            "title": "Who commissions Trendyol integration?",
            "intro": "“Trendyol integration” is a marketplace API order. Shoppers who want their own store go to e-commerce. Ozturksoft does not sell a boxed marketplace pack; orders, stock and ERP are written to your flow.",
            "i1": "Orders are copied from the panel, stock goes negative at night. The API should pull; stock should write back.",
            "i2": "Hepsiburada or N11 should share the same stock. A second channel is added to the same spine.",
            "i3": f"Invoices should cut from Logo. {a('/e-fatura-entegrasyonu', 'E-invoice', TY)} and {a('/logo-netsis-entegrasyon', 'ERP', TY)} are the same Çankaya team.",
            "i4": f"You also want a brand store. The site is a {a('/e-ticaret-sitesi-yaptirmak', 'separate URL', TY)}; stock is one source.",
            "outro": f"Free discovery: {tel(TY)}.",
        },
        "faq": {
            "title": "FAQ",
            "q1": "How much does Trendyol integration cost?",
            "a1": "Orders 25,000–50,000 TL (2–4 weeks), stock+shipping 50,000–95,000 TL, ERP 95,000–180,000 TL. Discovery is free.",
            "q2": "Is this an e-commerce site?",
            "a2": f"No. Your own store is {a('/e-ticaret-sitesi-yaptirmak', 'have an e-commerce site built', TY)}. This page is the Trendyol/marketplace API.",
            "q3": "Can Hepsiburada be added?",
            "a3": "Yes. A second marketplace is written onto the same stock spine. Price follows channel count in discovery.",
            "q4": "Do orders post to Logo?",
            "a4": f"Yes. A {a('/logo-netsis-entegrasyon', 'Logo / Netsis', TY)} voucher and optional {a('/e-fatura-entegrasyonu', 'e-invoice', TY)} in the same project.",
        },
        "cta": {
            "btn": "Free discovery call",
            "title": "Let’s talk through marketplace flow",
            "desc": f"Free discovery — orders, stock, ERP. {tel(TY)}",
            "btn2": "Get a free quote",
        },
        "footer": "© 2026 Ozturksoft — Trendyol integration",
        "related": {
            "shop": "Have e-commerce built",
            "ef": "E-invoice",
            "logo": "Logo Netsis",
            "wa": "WhatsApp chatbot",
        },
        "meta": {"title": "Trendyol Integration | Orders & Stock | Ozturksoft"},
        "stats": {"s1l": "Order pull", "s2l": "Stock + shipping", "s3l": "Stock delivery"},
    },
    "danismanlikPage": {
        "hero": {
            "badge": "Roadmap · PoC · KVKK · +90 546 549 6806",
            "title": "Yapay Zeka Danışmanlığı",
            "desc": f"AI consulting: a ChatGPT account is not a strategy. Which process, which budget, does data leave — a written roadmap. Build is a separate order: {a('/yapay-zeka-entegrasyonu', 'integration', DN)}, {a('/chatbot-yaptirmak', 'chatbot', DN)}, {a('/ai-agent', 'agent', DN)}. Çankaya, free discovery. Guide: {a('/blog/yapay-zeka-danismanligi-isletmeler-rehberi-2026', 'consulting article', DN)}.",
        },
        "pricing": {
            "title": "AI consulting price (2026)",
            "intro": "Discovery is free. Roadmap and PoC are written deliverables; code is a separate quote. Bands are 2026 Ankara market.",
            "row1": "Discovery",
            "row2": "Roadmap",
            "row3": "PoC",
            "p1": "Free",
            "t1": "45–90 min",
            "t2": "1–3 weeks",
            "t3": "4–8 weeks",
            "linkAi": "Build: integration",
            "linkGuide": "Guide",
        },
        "cards": {
            "c1title": "🗺️ Process pick",
            "c1desc": "Support, documents, sales — which one makes money in 90 days. The list is written; there is no slide-only delivery.",
            "c1link": "Book discovery →",
            "c2title": "💰 Cost band",
            "c2desc": "Chatbot, RAG and agent are priced separately. No surprise. Build is quoted by the same team.",
            "c2link": "Integration price →",
            "c3title": "🔒 KVKK",
            "c3desc": f"Does data leave, is on-premise required. Architecture note for {a('/ankara-kamu-yapay-zeka', 'public sector', DN)} and holdings.",
            "c3link": "KVKK guide →",
            "c4title": "🛠️ Then code",
            "c4desc": f"Once the decision is clear, {a('/chatbot-yaptirmak', 'chatbot', DN)}, {a('/ai-agent', 'agent', DN)} or LLM is built by the same Çankaya team.",
            "c4link": "AI company →",
        },
        "who": {
            "title": "Who commissions consulting?",
            "intro": "“AI consulting” is the order when you do not yet know what to build. ChatGPT integration searchers go to the build page. Ozturksoft writes the path first; the same team can code if you want.",
            "i1": "Management said “do AI”, there is no process list. A 90-day path and budget band should be written.",
            "i2": f"You bought a boxed bot; it did not fit. A PoC should prove the right scenario; then {a('/chatbot-yaptirmak', 'chatbot', DN)} or {a('/ai-agent', 'agent', DN)}.",
            "i3": f"KVKK and public sector. Whether on-premise is required is written in discovery. Build is {a('/yapay-zeka-entegrasyonu', 'integration', DN)} or {a('/ankara-kamu-yapay-zeka', 'public-sector AI', DN)}.",
            "i4": f"You read the guide. The information article is {a('/blog/yapay-zeka-danismanligi-isletmeler-rehberi-2026', 'separate', DN)}; work starts on this page.",
            "outro": f"Free discovery: {tel(DN)}.",
        },
        "faq": {
            "title": "FAQ",
            "q1": "How much does AI consulting cost?",
            "a1": "Discovery is free. Roadmap 25,000–60,000 TL (1–3 weeks), PoC 40,000–80,000 TL. Software is a separate quote.",
            "q2": "How is it different from integration?",
            "a2": f"This page is where to start. Code lives on {a('/yapay-zeka-entegrasyonu', 'AI integration', DN)}, {a('/chatbot-yaptirmak', 'chatbot', DN)}, {a('/ai-agent', 'AI agent', DN)}.",
            "q3": "Is it slides only?",
            "a3": "No. Process list, cost band, 90-day sequence. The same team can implement if you want.",
            "q4": "Is discovery really free?",
            "a4": f"Yes. 45–90 min, no commitment. {a('/iletisim', 'Form', DN)} or {tel(DN)}.",
        },
        "cta": {
            "btn": "Free discovery call",
            "title": "Let’s talk through the roadmap",
            "desc": f"Free discovery — process, KVKK, budget. {tel(DN)}",
            "btn2": "Get a free quote",
        },
        "footer": "© 2026 Ozturksoft — AI consulting",
        "related": {
            "ai": "Integration",
            "bot": "Chatbot",
            "agent": "AI agent",
            "hub": "AI company",
            "guide": "Guide",
        },
        "meta": {"title": "AI Consulting | Roadmap | Ozturksoft"},
        "stats": {"s1n": "Free", "s1l": "Discovery call", "s2l": "Roadmap", "s3l": "PoC"},
    },
}

RELATED_EXTRAS = {
    "tr": {
        "eticaretPage": {"ty": "Trendyol entegrasyonu", "ef": "E-fatura"},
        "faturaOkumaPage": {"ef": "E-fatura entegrasyonu"},
    },
    "en": {
        "eticaretPage": {"ty": "Trendyol integration", "ef": "E-invoice"},
        "faturaOkumaPage": {"ef": "E-invoice integration"},
    },
    "de": {
        "eticaretPage": {"ty": "Trendyol-Anbindung", "ef": "E-Rechnung"},
        "faturaOkumaPage": {"ef": "E-Rechnung-Anbindung"},
    },
    "fr": {
        "eticaretPage": {"ty": "Intégration Trendyol", "ef": "E-facture"},
        "faturaOkumaPage": {"ef": "Intégration e-facture"},
    },
    "ar": {
        "eticaretPage": {"ty": "تكامل ترينديول", "ef": "الفاتورة الإلكترونية"},
        "faturaOkumaPage": {"ef": "تكامل الفاتورة الإلكترونية"},
    },
    "ru": {
        "eticaretPage": {"ty": "Интеграция Trendyol", "ef": "E-factura"},
        "faturaOkumaPage": {"ef": "Интеграция e-factura"},
    },
}


def main() -> None:
    ns: dict = {}
    exec((Path(__file__).with_name("lp_i18n_rest.py")).read_text(encoding="utf-8"), ns)
    PACKS.update(ns["REST"])
    for lang, pages in PACKS.items():
        path = I18N / f"{lang}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        data.update(pages)
        extras = RELATED_EXTRAS.get(lang, {})
        for parent, keys in extras.items():
            data.setdefault(parent, {}).setdefault("related", {}).update(keys)
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"updated {path.name} keys={list(pages)}")


if __name__ == "__main__":
    main()
